fails:Exception#exception returns an exception of the same class as self with the message given as argument
fails:Exception#exception returns an exception of the same class as self with the message given as argument, but without reinitializing
